# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sid', models.CharField(max_length=10)),
                ('link', models.URLField()),
                ('crawled_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('crawled_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawled_date', models.DateTimeField(auto_now_add=True)),
                ('review_id', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('certified_buyer', models.BooleanField(default=False)),
                ('review_date', models.DateTimeField()),
                ('product_rating', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('upvotes', models.PositiveSmallIntegerField()),
                ('total_votes', models.PositiveSmallIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.Product')),
            ],
        ),
    ]
