# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='total',
            field=models.SmallIntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='product',
            name='total',
            field=models.SmallIntegerField(default=0),
        ),
    ]
