# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crawler', '0002_auto_20160408_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductJudgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judgement', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewJudgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judgement', models.TextField()),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.Review')),
            ],
        ),
    ]
